export const ADD_TRAVELER = 'ADD_TRAVELER';
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';
export const FETCHING_TRIP = 'FETCHING_TRIP';
export const GET_TRIP_SUCCESS = 'GET_TRIP_SUCCESS';
export const GET_TRIPS_SUCCESS = 'GET_TRIPS_SUCCESS';
